name: Compile LaTeX Document and Push PDF

on:
  pull_request:
    branches:
      - main # or any branch you want to trigger the workflow

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4 # Use the latest version

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3 # Use version 3
        with:
          root_file: bylaws.tex # Replace with your main .tex file
          working_directory: . # Or the directory where your .tex file is located
          compiler: pdflatex # or xelatex, lualatex, etc.

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4 # Use the latest version
        with:
          name: ByLaws
          path: bylaws.pdf # Replace with the name of your compiled PDF

      - name: Commit and push PDF
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add bylaws.pdf
          git commit -m "Update compiled PDF" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF##refs/heads/}
