name: Compile LaTeX on Pull Request

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }} # Checkout the PR branch

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: bylaws.tex
          working_directory: .
          compiler: pdflatex

      - name: Commit and push PDF to PR branch
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add bylaws.pdf
          git commit -m "Update compiled PDF" || echo "No changes to commit"
          git push origin HEAD:${{ github.head_ref }}
